name: Update Fork

on:
  schedule:
    - cron:  "*/10 * * * *"
    
jobs:
  update:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name:  Set Up Git
        run: |
          git config --global user.email "northstarstaking@gmail.com"
          git config --user.name "interruptRQ-c"
      
      - name:  Add Upstream Remote
        run: |
          git remote add upstream https://github.com/saekizm/pirateswap.git
      
      - name:  Fetch Upstream Changes
        run: |
          git fetch upstream
      
      - name:  Merge Upstream Changes
        run: |
          git merge upstream/main
      
      - name:  Push Changes to Fork
        run: |
          git push origin main
