name: Update Fork

on:
  schedule:
    - cron:  "*/15 * * * *"
  workflow_dispatch:
    
jobs:
  update:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    

      - name:  Set Up Git
        run: |
          git config --global user.email "northstarstaking@gmail.com"
          git config --global user.name "interruptRQ-c"
      
      - name:  Add Upstream Remote
        run: |
          git remote add upstream https://github.com/saekizm/pirateswap.git
      
      - name:  Fetch Upstream Changes
        run: |
          git fetch upstream
      
      - name:  Merge Upstream Changes
        run: |
          git checkout main
          git merge --allow-unrelated-histories upstream/main
          git merge upstream/main

            if git diff --name-only | grep -q .; then
              echo "Conflicts detected.  Resolving"
              for file in $(git diff --name-only); do
                git checkout --theirs "$file"
                git add "$file"
                git checkout --theirs ".github/workflows/update-fork.yaml"
                git add ".github/workflows/update-fork.yaml"
                # git checkout --ours "update-fork.yaml"
                # git add "update-fork.yaml"
              done
              git commit - m "conflict resolved"
            else
              echo "No conflicts detected"
            fi
          #git rebase --continue
      
      - name:  Push Changes to Fork
        run: |
          git pull
          if [ $? eq 0 ]; then
            echo "Already up to date";
            exit 0; # Exit without pushing
          else
            echo  "Local branch is ahead.  Proceeding with the push.";
            git push -f origin deploy;
          fi
